# Generated by Django 3.2.9 on 2022-03-12 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_rename_post_comment_detil'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commenter', models.CharField(max_length=50)),
                ('body', models.TextField()),
                ('detil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reply', to='blogs.comment')),
            ],
        ),
    ]
