# Generated by Django 3.2.9 on 2022-03-23 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0006_auto_20220323_0143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='commenter',
        ),
        migrations.RemoveField(
            model_name='commentreply',
            name='commenter',
        ),
    ]
