# Generated by Django 3.2.9 on 2022-03-26 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0010_auto_20220326_0315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentreply',
            name='detil',
        ),
        migrations.RemoveField(
            model_name='commentreply',
            name='user',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='CommentReply',
        ),
    ]
