# Generated by Django 3.2.9 on 2022-04-02 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0015_help'),
    ]

    operations = [
        migrations.AlterField(
            model_name='help',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
