# Generated by Django 3.2.9 on 2022-04-02 12:21

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blogs', '0016_alter_help_created'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Help',
            new_name='RoommateHelp',
        ),
    ]
