# Generated by Django 3.2.9 on 2022-04-03 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0018_carousel'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='post_image',
            field=models.ImageField(blank=True, null=True, upload_to='Post-img'),
        ),
    ]
