# Generated by Django 3.2.9 on 2022-04-05 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0021_alter_comment_comment_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Carousel',
        ),
        migrations.RemoveField(
            model_name='commentreply',
            name='detil',
        ),
        migrations.RemoveField(
            model_name='commentreply',
            name='user',
        ),
        migrations.RemoveField(
            model_name='roommatehelp',
            name='user',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='CommentReply',
        ),
        migrations.DeleteModel(
            name='RoommateHelp',
        ),
    ]
