# Generated by Django 3.2.9 on 2022-04-05 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0023_auto_20220405_2132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='polytechnic',
            name='reporter',
        ),
        migrations.RemoveField(
            model_name='scholarship',
            name='reporter',
        ),
        migrations.RemoveField(
            model_name='university',
            name='reporter',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='col',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='poly',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='sch',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='uni',
        ),
        migrations.DeleteModel(
            name='Colledge',
        ),
        migrations.DeleteModel(
            name='Polytechnic',
        ),
        migrations.DeleteModel(
            name='Scholarship',
        ),
        migrations.DeleteModel(
            name='University',
        ),
    ]
