# Generated by Django 3.2.9 on 2022-04-05 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0026_article_carousel_comment_commentreply_roommatehelp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='reporter',
        ),
        migrations.DeleteModel(
            name='Carousel',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='detil',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='commentreply',
            name='detil',
        ),
        migrations.RemoveField(
            model_name='commentreply',
            name='user',
        ),
        migrations.RemoveField(
            model_name='roommatehelp',
            name='user',
        ),
        migrations.DeleteModel(
            name='Article',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='CommentReply',
        ),
        migrations.DeleteModel(
            name='RoommateHelp',
        ),
    ]
