# Generated by Django 3.2.9 on 2022-04-07 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0028_article_carousel_comment_commentreply_roommatehelp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
