# Generated by Django 3.2.9 on 2022-04-07 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0032_alter_comment_comment_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='comment_image',
        ),
    ]
