# Generated by Django 3.2.9 on 2022-04-08 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0039_alter_comment_comment_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='post_image',
            field=models.ImageField(blank=True, null=True, upload_to='Post-img/'),
        ),
    ]
