# Generated by Django 3.2.9 on 2022-04-11 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0040_alter_article_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='post_image',
            field=models.ImageField(blank=True, default='about.jpg', null=True, upload_to='Post-img/'),
        ),
    ]
