# Generated by Django 3.2.9 on 2022-04-12 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0042_alter_article_post_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('AM', 'Automobile'), ('Com', 'Computer'), ('Ph', 'Phone'), ('Others', 'Others')], max_length=10)),
                ('product_image', models.ImageField(blank=True, default='view.jpg', null=True, upload_to='')),
            ],
        ),
    ]
