# Generated by Django 3.2.9 on 2022-04-12 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0047_alter_market_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='market',
            name='category',
            field=models.CharField(choices=[('Automobile', 'Automobile'), ('Computer', 'Computer'), ('Phone', 'Phone'), ('Others', 'Others')], max_length=10),
        ),
    ]
