# Generated by Django 3.2.9 on 2022-04-12 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0048_alter_market_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='market',
            name='contact_details',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
