# Generated by Django 3.2.9 on 2022-04-14 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0049_market_contact_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='market',
            name='product_image',
            field=models.FileField(blank=True, default='view.jpg', null=True, upload_to=''),
        ),
    ]
