# Generated by Django 3.2.9 on 2022-04-18 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0051_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
