# Generated by Django 3.2.9 on 2022-04-28 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0054_alter_market_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='market',
            name='product_image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
