# Generated by Django 3.2.9 on 2022-04-28 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0056_auto_20220428_1611'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roommatehelp',
            name='help_file',
        ),
    ]
